{% set name = "picojson" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kazuho/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 056805ca2691798f5545935a14bb477f2e1d827c9fb862e6e449dbea22801c7d
  patches:
    - patches/0001-Add-CMake-config-file-package-to-install.patch

build:
  ignore_run_exports:
    # package is header-only
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/picojson/picojson.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/picojson/picojson-targets.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/picojson/picojson-config-version.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/picojson/picojson-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\picojson\picojson.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\picojson\picojson-targets.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\picojson\picojson-config-version.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\picojson\picojson-config.cmake exit 1  # [win]

about:
  home: https://github.com/kazuho/picojson
  dev_url: https://github.com/kazuho/picojson.git
  summary: a header-file-only, JSON parser serializer in C++
  license: BSD-2-Clause
  license_file: LICENSE
  description: |
    PicoJSON is a tiny JSON parser / serializer for C++ with following properties:

    - header-file only
    - no external dependencies (only uses standard C++ libraries)
    - STL-frendly (arrays are represented by using `std::vector`, objects are `std::map`)
    - provides both pull interface and streaming (event-based) interface

extra:
  recipe-maintainers:
    - duncanmmacleod
    - eaaltonen
